Repository jaspermayone/ai-fine-tuning, pull requests merged in 2024-07, with the labels that each got.

#1 Classify 10, 11, 12
  README.md
Labels: size/XS

#2 initial labels for some files
  README.md
  data/16.json
  data/17.json
  data/18.json
  data/63.json
Labels: size/L

#6 Added 58-62
  README.md
  data/58.json
  data/59.json
  data/60.json
  data/61.json
  data/62.json
Labels: size/L

#4 Classify 20-39
  README.md
  data/20.json
  data/21.json
  data/22.json
  data/23.json
  data/24.json
  data/25.json
  data/26.json
  data/27.json
  data/28.json
  data/29.json
  data/30.json
  data/31.json
  data/32.json
  data/33.json
  data/34.json
  data/35.json
  data/36.json
  data/37.json
  data/38.json
  data/39.json
Labels: size/XL

#3 Classify 1-15
  README.md
  data/1.json
  data/10.json
  data/11.json
  data/12.json
  data/13.json
  data/14.json
  data/15.json
  data/2.json
  data/3.json
  data/4.json
  data/5.json
  data/6.json
  data/7.json
  data/8.json
  data/9.json
Labels: size/L

#7 #19 & readme update
  README.md
  data/19.json
Labels: size/M
